server:
  port: 8010

spring:
  application:
    name: education-service-8001
  cloud:
    nacos:
      discovery:
        #        本地nacos地址
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/safe_school?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        #        暴露所有端点给管理端点，用于被监控
        include: '*'